name: 'Setup Package dependencies'
description: 'based on r-lib/actions/setup-r-dependencies but with extra options for ospsuite packages'
author: 'Felix MIL'

inputs:
  RCLR_VERSION:
    description: 'The version of rClr to install'
    required: true
  extra-packages:
    description: 'Extra packages to install defined as described in https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies and https://r-lib.github.io/pkgdepends/reference/pkg_refs.html#github-packages-github-'
    default: "|
      rClr=local::./rClr_${{ inputs.RCLR_VERSION }}.zip
      ospsuite.utils=github::Open-Systems-Pharmacology/OSPSuite.RUtils
      tlf=github::Open-Systems-Pharmacology/TLF-Library
      ospsuite=github::Open-Systems-Pharmacology/OSPSuite-R
      ospsuite.parameteridentification=github::Open-Systems-Pharmacology/OSPSuite.ParameterIdentification"

runs:
  using: "composite"
  steps:
   - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::devtools
            any::covr
            any::pkgdown
            local::.
            ${{ inputs.extra-packages }}
