name: 'Install rClr'
description: 'Download a rClr build and install it.'
author: 'Felix MIL'

inputs:
  RCLR_VERSION:
    description: 'The version of rClr to install'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download rClr
      run: |
        RCLR_URL <- "https://github.com/Open-Systems-Pharmacology/rClr/releases/download/v${{ inputs.RCLR_VERSION }}/rClr_${{ inputs.RCLR_VERSION }}.zip"
        download.file(RCLR_URL, "rClr_${{ inputs.RCLR_VERSION }}.zip")
      shell: Rscript {0}
    - name: Install rClr
      run: |
        install.packages("./rClr_${{ inputs.RCLR_VERSION }}.zip", type = "binary")
      shell: Rscript {0}
