on:
  workflow_call:
    inputs:
      RCLR_VERSION:
        required: true
        type: 'string'
    secrets:
      GITHUB_TOKEN:
        required: true

name: test-pkg-and-coverage

jobs:
  test-pkg-and-coverage:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install PK-Sim
        uses: ./.github/actions/install-PKSIM.yml

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install rClr
        uses: ./.github/actions/install-rClr.yml
        with:
          RCLR_VERSION: ${{ inputs.RCLR_VERSION }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            rClr=local::./rClr_${{ env.RCLR_VERSION }}.zip
            any::covr
            local::.
            ospsuite.utils=github::Open-Systems-Pharmacology/OSPSuite.RUtils
            tlf=github::Open-Systems-Pharmacology/TLF-Library
            ospsuite=github::Open-Systems-Pharmacology/OSPSuite-R
            ospsuite.parameteridentification=github::Open-Systems-Pharmacology/OSPSuite.ParameterIdentification
          needs: coverage

      - name: Test coverage
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
